#!/bin/bash

echo "🔄 Loading Sample Data for Dashboard Testing"
echo ""
echo "🎯 Target: https://68635df5902bc8983b5fe841--complyze.netlify.app"
echo ""

# Instructions for the user
echo "📋 To load sample data into your dashboard:"
echo ""
echo "1. 🌐 Open your browser and go to:"
echo "   https://68635df5902bc8983b5fe841--complyze.netlify.app/dashboard"
echo ""
echo "2. 🔑 Make sure you're logged in (you should see the dashboard)"
echo ""
echo "3. 🛠️ Open Browser Developer Tools:"
echo "   - Right-click → Inspect"
echo "   - Or press F12"
echo "   - Go to Console tab"
echo ""
echo "4. 📝 Paste this JavaScript code in the console:"
echo ""
echo "// Load sample data for current user"
echo "fetch('/api/load-sample-data', {"
echo "  method: 'POST',"
echo "  headers: {"
echo "    'Authorization': 'Bearer ' + localStorage.getItem('complyze_token')"
echo "  }"
echo "})"
echo ".then(response => response.json())"
echo ".then(data => {"
echo "  console.log('Sample data result:', data);"
echo "  if (data.message) {"
echo "    alert('✅ ' + data.message + ' - Refresh the page to see data!');"
echo "  } else {"
echo "    alert('❌ Error: ' + (data.error || 'Unknown error'));"
echo "  }"
echo "})"
echo ".catch(error => {"
echo "  console.error('Error:', error);"
echo "  alert('❌ Network error: ' + error.message);"
echo "});"
echo ""
echo "5. 🔄 After running the script, refresh the dashboard page"
echo ""
echo "🎉 You should now see:"
echo "   • Budget tracking with costs"
echo "   • Top 5 most expensive prompts"
echo "   • Risk trends and analytics"
echo "   • Model usage statistics"
echo "   • All dashboard cards populated with data"
echo ""
echo "💡 If you get 'User already has X prompt events', that means data is already loaded!"
echo "   Just refresh the page to see it." 