[build]
  base = "complyze"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js plugin for proper handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (you'll need to set these in Netlify dashboard)
# The following are examples - set the actual values in Netlify dashboard
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://your-domain.netlify.app"
  NODE_ENV = "production"

# Next.js redirects - let the plugin handle routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Ensure API routes work properly
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 